export const portfolioList = [
  {
    id: 1,
    title: "Vélo Expresso",
    imageDestop: "/images/veloexpresso-desktop.png",
    imageMobile: "/images/veloexpresso-mobile.png",
    description:
      "Site vitrine pour une entreprise de location de vélos électriques.",
    link: "https://velo-expresso-front.vercel.app/",
    githubFront: "",
    githubBack: "",
    technos: "NextJs, TailwindCSS, PHP, MySQL",
    more: "Ce projet part d'une idée de site vitrine, réactif lors de la navigation. NextJS s'est imposé évidemment. Mais dès le début de la réflexion, nous nous sommes rendu compte que le propriétaire du magasin aurait besoin d'un outil d'administration pour les vélos, tarifs, prestations... Nous avons donc décidé de faire un second site en php pour la gestion des données.",
  },
  {
    id: 2,
    title: "Un poseur de cuisines",
    imageDestop: "/images/cuisine-desktop.png",
    imageMobile: "/images/cuisine-mobile.png",
    description: "Site vitrine pour un artisan poseur de cuisines.",
    link: "https://christophe-cuisine.fr/",
    githubFront: "",
    githubBack: "",
    technos: "React, TailwindCSS",
    more: "Ce projet est un site vitrine pour un artisan.Pour moi même en fait 😅 !  Je passe de la conception de cuisisnes à la conception de site et outils web. Développé en React et statique, l'idée était d'être simple et sobre dans la réalisation pour un lisibilité maximale. Ce n'était pas prévu, mais cette production m'a ramené plus de clients que nécessaire !",
  },
  {
    id: 3,
    title: "un blog",
    imageDestop: "/images/blog-desktop.png",
    imageMobile: "/images/blog-mobile.png",
    description: "Un blog pour partager mes expériences et mes projets.",
    link: "https://blog.barpat.fun/",
    githubFront: "",
    githubBack: "",
    technos: "php, bootstrap",
    more: "Dans le cadre d'une formation, nous devions exploiter php et une architecture MVC. J'ai donc décidé de créer un blog pour partager mes expériences et mes projets. J'ai utilisé bootstrap pour le design et php pour la gestion des données. Les articles sont stockés dans une base de données MySQL. L'administrateur a accés à un tableau de bord pour la gestion des articles, des utilisateurs. Il peut écrire, modifier, supprimer les articles. Il peut aussi gérer les utilisateurs, les rôles, les droits. Un projet complet pour une formation complète.",
  },
  {
    id: 4,
    title: "Mon CV en ligne",
    imageDestop: "/images/cv-desktop.png",
    imageMobile: "/images/cv-mobile.png",
    description: "Mon CV en ligne, pour m'amuser avec React.",
    link: "https://barpat.fun/",
    githubFront: "",
    githubBack: "",
    technos: "React, sass",
    more: "PArce que c'est à travers des projets perso qu'on apprend le plus lors de notre formation, j'ai réalisé un site de présentation. PAs un CVV des plus sérieux, mais un site qui me ressemble. J'ai utilisé React pour la dynamique et sass pour le design. J'ai aussi utilisé des animations pour rendre le site plus vivant. La librairie GSAP est vraiment complète pour ce genre de projet.",
  },
];
